#tlsConfig :
 # Certificate and key files for server to use to authenticate to client
# tlsCertPath : "https/testdata/server.crt"
# tlsKeyPath : "https/testdata/server.key"
 
 # Server policy for client authentication. Maps to ClientAuth Policies
 # For more detail on clientAuth options: [ClientAuthType](https://golang.org/pkg/crypto/tls/#ClientAuthType)
# [clientAuth : <string> | default = "NoClientCert" ]
  
 # CA certificate for client certificate authentication to the server
 # clientCAs : "<filename>" 
